varnum1=int(input("Please Input the number to print the tables of: "))
print(varnum1*1)
print(varnum1*2)
print(varnum1*3)
print(varnum1*4)
print(varnum1*5)
print(varnum1*6)
print(varnum1*7)
print(varnum1*8)
print(varnum1*9)
print(varnum1*10)
